### ISSUE TITLE
I can't clonning this repository

### ISSUE THREAD

**Issue by nvil** [testing-agent/droidagent#1]
I'm trying to clone this repository in git, but it fails when I try to make the droidbot module a submodule - the submodule link appears to be broken.

**Comment by Shengyun-Si** [comment]
same issue

**Comment by greenmonn** [comment]
Seems that the submodule path was outdated due to the repository transfer from the anonymous account :( I just pushed a new commit to fix this and now you should be able to clone the full code via the command `git clone --recurse-submodule https://github.com/coinse/droidagent.git` - Let me know if the issue persists @nvil @GeekerSsy and thanks for your interests!

**Comment by nvil** [comment]
I can't clone still this repository
Error messages from command shell.
-----------------------
C:\Work>git clone --recurse-submodule https://github.com/coinse/droidagent.git
Cloning into 'droidagent'...
remote: Enumerating objects: 519, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 519 (delta 13), reused 38 (delta 10), pack-reused 452
Receiving objects: 100% (519/519), 37.00 MiB | 20.37 MiB/s, done.
Resolving deltas: 100% (177/177), done.
sh: warning: setlocale: LC_ALL: cannot change locale (ko_KR_UTF-8): No such file or directory
Submodule 'droidbot' (git@github.com:coinse/droidbot.git) registered for path 'droidbot'
Cloning into 'C:/Work/droidagent/droidbot'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:coinse/droidbot.git' into submodule path 'C:/Work/droidagent/droidbot' failed
Failed to clone 'droidbot'. Retry scheduled
Cloning into 'C:/Work/droidagent/droidbot'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:coinse/droidbot.git' into submodule path 'C:/Work/droidagent/droidbot' failed
Failed to clone 'droidbot' a second time, aborting

####
And I tried to clone it with another tool, Fork
But I got to fail.

remote: Not Found
fatal: repository 'https://github.com/coinse/droidagent.git/droidbot/' not found
fatal: clone of 'https://github.com/coinse/droidagent.git/droidbot' into submodule path 'C:/Work/git/droidagent/droidbot' failed
Failed to clone 'droidbot'. Retry scheduled

**Comment by greenmonn** [comment]
Ah, My bad to set the submodule url in the form requiring owner's ssh authentication.. Fixed it again and I checked in a fresh environment without my ssh setting. Does the cloning work now for you?

**Comment by nvil** [comment]
I noticed that I couldn't clone via SSH from my office, and it seemed to be a firewall issue, so I changed the .gitmodule file for https and it works! You did the same thing a few minutes ago. Thanks.

**Comment by Shengyun-Si** [comment]
> Seems that the submodule path was outdated due to the repository transfer from the anonymous account :( I just pushed a new commit to fix this and now you should be able to clone the full code via the command `git clone --recurse-submodule https://github.com/coinse/droidagent.git` - Let me know if the issue persists @nvil @GeekerSsy and thanks for your interests!

hey thank you for your quick fix. For me the issue was solved.
